CREATE SEQUENCE SEQ_PAYMENT_METHOD START WITH 1 INCREMENT BY 1;
CREATE TABLE PAYMENT_METHOD (
    ID          INTEGER         NOT NULL DEFAULT nextval('SEQ_PAYMENT_METHOD'),
    CODE        VARCHAR(2)      NOT NULL,
    NAME        VARCHAR(100)    NOT NULL,
    STATUS      VARCHAR(20)     NOT NULL,
    CREATED_AT  TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY (ID),
CONSTRAINT UK_PAYMENT_METHOD_CODE UNIQUE (CODE)
);

CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE TABLE USERS (
    ID          INTEGER         NOT NULL DEFAULT nextval('SEQ_USERS'),
    NAME        VARCHAR(100)    NOT NULL,
    EMAIL       VARCHAR(150)    NOT NULL,
    PASSWORD    VARCHAR(255)    NOT NULL,
    ROLE        VARCHAR(30)     NOT NULL,
    STATUS      VARCHAR(20)     NOT NULL,
    CREATED_AT  TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_USERS PRIMARY KEY (ID),
CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE SEQUENCE SEQ_ORDERS START WITH 1 INCREMENT BY 1;
CREATE TABLE ORDERS (
    ID              INTEGER         NOT NULL DEFAULT nextval('SEQ_ORDERS'),
    CODE            VARCHAR(50)     NOT NULL,
    OBSERVATIONS    TEXT,
    ORDER_STATUS    VARCHAR(30)     NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
CONSTRAINT UK_ORDERS_CODE UNIQUE (CODE)
);

CREATE SEQUENCE SEQ_SALE START WITH 1 INCREMENT BY 1;
CREATE TABLE SALE (
    ID          INTEGER         NOT NULL DEFAULT nextval('SEQ_SALE'),
    AMOUNT      NUMERIC(10,2)   NOT NULL,
    DISCOUNT    NUMERIC(10,2),
    FK_USER     INTEGER         NOT NULL,
    FK_ORDER    INTEGER         NOT NULL,
    STATUS      VARCHAR(20)     NOT NULL,
    CREATED_AT  TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_SALE PRIMARY KEY (ID),
CONSTRAINT FK_SALE_USER     FOREIGN KEY (FK_USER)   REFERENCES USERS (ID),
CONSTRAINT FK_SALE_ORDER    FOREIGN KEY (FK_ORDER)  REFERENCES ORDERS (ID)
);

CREATE SEQUENCE SEQ_INSTALLMENT START WITH 1 INCREMENT BY 1;
CREATE TABLE INSTALLMENT (
    ID                  INTEGER         NOT NULL DEFAULT nextval('SEQ_INSTALLMENT'),
    NUMBER              INTEGER         NOT NULL,
    AMOUNT              NUMERIC(10,2)   NOT NULL,
    DUE_DATE            DATE            NOT NULL,
    FK_SALE             INTEGER         NOT NULL,
    FK_PAYMENT_METHOD   INTEGER         NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    CREATED_AT          TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_INSTALLMENT PRIMARY KEY (ID),
CONSTRAINT FK_INSTALLMENT_SALE              FOREIGN KEY (FK_SALE)           REFERENCES SALE (ID),
CONSTRAINT FK_INSTALLMENT_PAYMENT_METHOD    FOREIGN KEY (FK_PAYMENT_METHOD) REFERENCES PAYMENT_METHOD (ID)
);

CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 1;
CREATE TABLE ITEM (
    ID              INTEGER         NOT NULL DEFAULT nextval('SEQ_ITEM'),
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     TEXT,
    PRICE           NUMERIC(10,2)   NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_ITEM PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ORDER_ITEM START WITH 1 INCREMENT BY 1;
CREATE TABLE ORDER_ITEM (
    ID          INTEGER         NOT NULL DEFAULT nextval('SEQ_ORDER_ITEM'),
    QUANTITY    INTEGER         NOT NULL,
    AMOUNT      NUMERIC(10,2),
    FK_ORDER    INTEGER         NOT NULL,
    FK_ITEM     INTEGER         NOT NULL,
CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ID),
CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY  (FK_ORDER)  REFERENCES ORDERS (ID),
CONSTRAINT FK_ORDER_ITEM_ITEM FOREIGN KEY   (FK_ITEM)   REFERENCES ITEM (ID)
);

CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1;
CREATE TABLE PRODUCT (
    ID              INTEGER         NOT NULL DEFAULT nextval('SEQ_PRODUCT'),
    NAME            VARCHAR(100)    NOT NULL,
    MINIMUM_STOCK   INTEGER         NOT NULL DEFAULT 0,
    UNIT_MEASURE    VARCHAR(20),
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_PRODUCT_ITEM START WITH 1 INCREMENT BY 1;
CREATE TABLE PRODUCT_ITEM (
    ID          INTEGER     NOT NULL DEFAULT nextval('SEQ_PRODUCT_ITEM'),
    QUANTITY    INTEGER     NOT NULL,
    FK_ITEM     INTEGER     NOT NULL,
    FK_PRODUCT  INTEGER     NOT NULL,
CONSTRAINT PK_PRODUCT_ITEM PRIMARY KEY (ID),
CONSTRAINT FK_PRODUCT_ITEM_ITEM FOREIGN KEY     (FK_ITEM)       REFERENCES ITEM (ID),
CONSTRAINT FK_PRODUCT_ITEM_PRODUCT FOREIGN KEY  (FK_PRODUCT)    REFERENCES PRODUCT (ID)
);

CREATE SEQUENCE SEQ_STOCK START WITH 1 INCREMENT BY 1;
CREATE TABLE STOCK (
    ID          INTEGER         NOT NULL DEFAULT nextval('SEQ_STOCK'),
    TYPE        VARCHAR(20)     NOT NULL,
    QUANTITY    INTEGER         NOT NULL,
    STATUS      VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT  TIMESTAMP       NOT NULL DEFAULT NOW(),
CONSTRAINT PK_STOCK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_STOCK_MOVEMENT START WITH 1 INCREMENT BY 1;
CREATE TABLE STOCK_MOVEMENT (
    ID          INTEGER     NOT NULL DEFAULT nextval('SEQ_STOCK_MOVEMENT'),
    TYPE        VARCHAR(20) NOT NULL,
    QUANTITY    INTEGER     NOT NULL,
    FK_STOCK    INTEGER     NOT NULL,
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
CONSTRAINT PK_STOCK_MOVEMENT PRIMARY KEY (ID),
CONSTRAINT FK_STOCK_MOVEMENT_STOCK FOREIGN KEY (FK_STOCK) REFERENCES STOCK (ID)
);