INSERT INTO PAYMENT_METHOD (CODE, NAME, STATUS)
VALUES
('01', 'DINHEIRO', 'ACTIVE'),
('02', 'CHEQUE', 'ACTIVE'),
('03', 'CARTÃO DE CRÉDITO', 'ACTIVE'),
('04', 'CARTÃO DE DÉBITO', 'ACTIVE'),
('05', 'CRÉDITO LOJA', 'ACTIVE'),
('10', 'VALE ALIMENTAÇÃO', 'ACTIVE'),
('11', 'VALE REFEIÇÃO', 'ACTIVE'),
('12', 'VALE PRESENTE', 'ACTIVE'),
('13', 'VALE COMBUSTÍVEL', 'ACTIVE'),
('15', 'BOLETO BANCÁRIO', 'ACTIVE'),
('16', 'DEPÓSITO BANCÁRIO', 'ACTIVE'),
('17', 'PIX', 'ACTIVE'),
('18', 'TRANSFERÊNCIA BANCÁRIA', 'ACTIVE'),
('19', 'PROGRAMA DE FIDELIDADE', 'ACTIVE'),
('90', 'SEM PAGAMENTO', 'ACTIVE'),
('99', 'OUTROS', 'ACTIVE');